apiVersion : apps/v1
kind: Deployment
metadata:
  name: anveshmydemokubepython 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anveshmydemokubepython
  template:
    metadata:
      labels:
        app: anveshmydemokubepython 
    spec:
      containers:
        - name: anveshmydemokubepython 
          image: demokubepythonacr.azurecr.io/anveshmydemokubepython
          ports:
          - containerPort: 2222